
SELECT * FROM RIESGO.INSTRUMENT

create table Instrument (
ID INT NOT NULL,
TICKER VARCHAR(255) NOT NULL,
INSTRUMENT_TYPE VARCHAR(255) NOT NULL,
PRIMARY KEY (ID,TICKER)
)

create table Bond_BD_TEST (
ID INT NOT NULL,
TICKER VARCHAR(255) NOT NULL,
INSTRUMENT_TYPE VARCHAR(255) NOT NULL,
MONEDA VARCHAR(255) NOT NULL,
TASA_CUPON NUMERIC(17,10),
NOMINAL NUMERIC(17,10),
TIPO_EMISION VARCHAR(255) NOT NULL,
YIELD_BASIS VARCHAR(255) NOT NULL,
YIELD_CALC_METHOD VARCHAR(255) NOT NULL,
PAYMENT_COMPOSITION VARCHAR(255) NOT NULL,
YIELD_COMPOSITION VARCHAR(255) NOT NULL,
FECHA_VENCIMIENTO DATE NOT NULL,
PRIMARY KEY (ID,TICKER)
)
--DROP TABLE Bond_BD_TEST
SELECT * FROM Bond_BD_TEST

INSERT INTO 
INSERT INTO Bond_BD_TEST
VALUES 
(value1, value2, value3, ...);

--S_UDIBONO_401115